use_frameworks!

platform :ios, '10.0'

target 'BNSegmentedControl_Example' do
  pod 'BNSegmentedControl', :path => '../'

  target 'BNSegmentedControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
